### ISSUE TITLE
Classes instead of IDs?

### ISSUE THREAD

**Issue by ericclemmons** [Nase00/react-shift#4]
In the event there are multiple `<Shift>` components per-URL, shouldn't elements use `className` instead of `id`?

**Comment by sowiecki** [comment]
Agreed. I need to overhaul the entire styling. Next version will replace classes and ids with props for `className` and `style`.

**Comment by sowiecki** [comment]
Published `2.0.1` which completely changes the styling system to use passed props for `className`'s and `style`'s on subcomponents. No more `id`'s anywhere.
